# **TENSORES**

## Gerando tensores

In [15]:
import torch

# Tensores com valores constantes
constants = torch.tensor([[3.1415, 2.7182], [1.6180, 0.0072]])
print(constants, '\n')

# Gerando um tensor vazio
print(torch.empty(2, 2), '\n')

# Gerando tensores de zeros
print(torch.zeros(5, 3), '\n')

# Gerando tensores de um
print(torch.ones(3, 3), '\n')

# Determinando o tipo primitivo
print(torch.ones((2, 2), dtype=torch.int16), '\n')

# Gerando tensores de números aleatórios
print(torch.rand(3, 2), '\n')

# Gerando tensores de números aleatórios a partir de sementes
torch.manual_seed(123)
print(torch.rand(1, 3), '\n')

# Transposição de tensores
print(torch.ones(3, 2).t())

tensor([[3.1415, 2.7182],
        [1.6180, 0.0072]]) 

tensor([[0.0000e+00, 7.2868e-44],
        [2.6395e-09, 8.1258e+20]]) 

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[1, 1],
        [1, 1]], dtype=torch.int16) 

tensor([[0.6886, 0.0740],
        [0.8665, 0.1366],
        [0.1025, 0.1841]]) 

tensor([[0.2961, 0.5166, 0.2517]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


## Operações Matemáticas

In [3]:
# Soma
ones = torch.ones(4, 3)
twos = ones + ones
print(twos, '\n')

# Subtração
ones = twos - ones
print(ones, '\n')

# Multiplicação
mult = twos.mm(ones.t())
print(mult, '\n')

# Valor absoluto
abs = torch.abs(torch.rand(3, 2) * (-1))
print(abs, '\n')

# Função seno
sin = torch.sin(torch.rand(2, 2))
print(sin, '\n')

# Algebra Linear (determinante)
det = torch.det(torch.rand(2, 2))
print(det)

# Estatística (média e máximo)
md = torch.std_mean(torch.rand(2, 3))
max = torch.max(torch.rand(2, 3))
print(md, max)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]) 

tensor([[0.6886, 0.0740],
        [0.8665, 0.1366],
        [0.1025, 0.1841]]) 

tensor([[0.6642, 0.3101],
        [0.6343, 0.0756]]) 

tensor(-0.1038)
(tensor(0.1719), tensor(0.6589)) tensor(0.9826)


# Shapes

In [13]:
x = torch.empty(2, 2, 2)
print(x.shape)

empty_like_x = torch.empty_like(x)
zeros_like_x = torch.zeros_like(x)
zeros_like_x

torch.Size([2, 2, 2])


tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])