In [ ]:
import torch

# Gerando tensores

In [46]:
# Gerando tensores de zeros
print(torch.zeros(5, 3), '\n')

# Gerando tensores de um
print(torch.ones(3, 3), '\n')

# Determinando o tipo primitivo
print(torch.ones((2, 2), dtype=torch.int16), '\n')

# Gerando tensores de números aleatórios
print(torch.rand(3, 2), '\n')

# Gerando tensores de números aleatórios a partir de sementes
torch.manual_seed(123)
print(torch.rand(1, 3), '\n')

# Transposição de tensores
print(torch.ones(3, 2).t())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[1, 1],
        [1, 1]], dtype=torch.int16) 

tensor([[0.6886, 0.0740],
        [0.8665, 0.1366],
        [0.1025, 0.1841]]) 

tensor([[0.2961, 0.5166, 0.2517]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


# Operações aritméticas

In [48]:
# Soma
ones = torch.ones(4, 3)
twos = ones + ones
print(twos, '\n')

# Subtração
ones = twos - ones
print(ones, '\n')

# Multiplicação
mult = twos.mm(ones.t())
print(mult)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
