In [34]:
import torch

# **TENSORES**

## Gerando tensores

In [2]:
# Gerando tensores de zeros
print(torch.zeros(5, 3), '\n')

# Gerando tensores de um
print(torch.ones(3, 3), '\n')

# Determinando o tipo primitivo
print(torch.ones((2, 2), dtype=torch.int16), '\n')

# Gerando tensores de números aleatórios
print(torch.rand(3, 2), '\n')

# Gerando tensores de números aleatórios a partir de sementes
torch.manual_seed(123)
print(torch.rand(1, 3), '\n')

# Transposição de tensores
print(torch.ones(3, 2).t())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[1, 1],
        [1, 1]], dtype=torch.int16) 

tensor([[0.4750, 0.0096],
        [0.6490, 0.5245],
        [0.2180, 0.9754]]) 

tensor([[0.2961, 0.5166, 0.2517]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


## Operações Matemáticas

In [33]:
# Soma
ones = torch.ones(4, 3)
twos = ones + ones
print(twos, '\n')

# Subtração
ones = twos - ones
print(ones, '\n')

# Multiplicação
mult = twos.mm(ones.t())
print(mult, '\n')

# Valor absoluto
abs = torch.abs(torch.rand(3, 2) * (-1))
print(abs, '\n')

# Função seno
sin = torch.sin(torch.rand(2, 2))
print(sin, '\n')

# Algebra Linear (determinante)
det = torch.det(torch.rand(2, 2))
print(det)

# Estatística (média e máximo)
md = torch.std_mean(torch.rand(2, 3))
max = torch.max(torch.rand(2, 3))
print(md, max)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]) 

tensor([[0.2132, 0.0206],
        [0.3247, 0.9355],
        [0.5855, 0.4695]]) 

tensor([[0.4969, 0.7255],
        [0.0584, 0.1140]]) 

tensor(0.1239)
(tensor(0.3907), tensor(0.3012)) tensor(0.9247)
